# Generated by Django 5.0.1 on 2024-02-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=30)),
                ('telephone_number', models.CharField(max_length=15, unique=True)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
    ]
