# Generated by Django 5.0.1 on 2024-02-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='Id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
